SHOW DATABASE;

CREATE DATABASE IF NOT EXISTS auth_user;

USE auth_user;

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
  password VARCHAR(255) NOT NULL
);

SHOW TABLES;

SELECT * FROM users;